name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"
      - "*.md"

  pull_request:
    branches: [main]
    paths-ignore:
      - ".github/**"
      - "*.md"

  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - uses: rrainn/dynamodb-action@v2.0.1
        with:
          port: 5000
          cors: "*"

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint -- --max-warnings=0
